steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-API
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/api:$COMMIT_SHA
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/api:latest
      - --context=./api
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-React
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/nginx:$COMMIT_SHA
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_LIFECYCLE}/nginx:latest
      - --context=./react
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: Gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ ${_USE_HELM} ]]; then
          gcloud container clusters get-credentials ${_CLUSTER} --zone=${_ZONE} --project=${_GKE_PROJECT}
        fi

  - name: "gcr.io/walker-cpl/helm"
    id: Helm-Upgrade
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ ${_USE_HELM} ]]; then
          make all NAMESPACE=${_APP_CODE} LIFECYCLE=${_LIFECYCLE} API_TAG=$COMMIT_SHA  NGINX_TAG=$COMMIT_SHA 
        fi
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"


timeout: 900s
# options:
#   machineType: E2_HIGHCPU_8


