steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-API
    args:
      - --destination=gcr.io/$PROJECT_ID/${_IMAGE_REPO_NAME}/api:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_IMAGE_REPO_NAME}/api:latest
      - --context=./api
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-React
    args:
      - --destination=gcr.io/$PROJECT_ID/${_IMAGE_REPO_NAME}/nginx:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_IMAGE_REPO_NAME}/nginx:latest
      - --context=./react
      - --cache=true
      - --cache-ttl=240h

timeout: 1200s
options:
  machineType: E2_HIGHCPU_8




