steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-API
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO_NAME}/api:$COMMIT_SHA
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO_NAME}/api:latest
      - --context=./api
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-React
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO_NAME}/nginx:$COMMIT_SHA
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO_NAME}/nginx:latest
      - --context=./react
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: Gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials ${_CLUSTER} --zone=${_ZONE} --project=${_GKE_PROJECT}

  - name: "gcr.io/walker-cpl/helm"
    id: Helm-Upgrade
    entrypoint: "bash"
    args:
      - "-c"
      - |
        helm dep update ./charts/web-app
        helm template ${_NAMESPACE} ./charts/web-app -f ./charts/web-app/values/${_LIFECYCLE}.yaml -n ${_NAMESPACE} --set web-app.api.tag=$COMMIT_SHA --set web-app.nginx.tag=$COMMIT_SHA --set web-app.db_project_id=${_DB_PROJECT} --set web-app.app_code=${_APP_CODE} --set web-app.domain=${_DOMAIN} --set google.registry=${_IMAGE_REPO_NAME} --set ip_name=${_IP_NAME} --set clean_data_bucket=${_CLEAN_DATA_BUCKET_NAME} --set ingest_bucket=${_INGEST_BUCKET_NAME}
        helm upgrade -i ${_NAMESPACE} ./charts/web-app -f ./charts/web-app/values/${_LIFECYCLE}.yaml -n ${_NAMESPACE} --create-namespace --set web-app.api.tag=$COMMIT_SHA --set web-app.nginx.tag=$COMMIT_SHA --set web-app.db_project_id=${_DB_PROJECT} --set web-app.app_code=${_APP_CODE} --set web-app.domain=${_DOMAIN} --set google.registry=${_IMAGE_REPO_NAME} --set ip_name=${_IP_NAME} --set clean_data_bucket=${_CLEAN_DATA_BUCKET_NAME} --set ingest_bucket=${_INGEST_BUCKET_NAME}
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"


timeout: 2400s
# options:
#   machineType: E2_HIGHCPU_8




