
steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-API
    args:
      - --destination=gcr.io/$PROJECT_ID/${_LIFECYCLE}/api:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_LIFECYCLE}/api:latest
      - --context=./api
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build-React
    args:
      - --destination=gcr.io/$PROJECT_ID/${_LIFECYCLE}/react:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/${_LIFECYCLE}/react:latest
      - --context=./react
      - --cache=true
      - --cache-ttl=240h

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: Gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials ${_CLUSTER} --zone=${_ZONE} --project=${_GKE_PROJECT}

  - name: "gcr.io/walker-cpl/helm"
    id: Helm-Upgrade
    entrypoint: "bash"
    args:
      - "-c"
      - |
        helm dep update ./charts/web-app
        helm upgrade -i ${_NAMESPACE} ./charts/web-app -f ./charts/web-app/values/${_LIFECYCLE}.yaml -n ${_NAMESPACE} --create-namespace --set web-app.api.tag=$COMMIT_SHA --set web-app.nginx.tag=$COMMIT_SHA --set web-app.db_project_id=${_DB_PROJECT} --set web-app.app_code=${_APP_CODE} --set web-app.google.domain=${_DOMAIN}
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"


timeout: 1200s
options:
  machineType: E2_HIGHCPU_8

