apiVersion: v1
kind: Pod
metadata:
  name: gcloud
  namespace: coleman
spec:
  containers:
  - image: google/cloud-sdk
    name: gcloud
    command: ["gcloud"]
    args: ["auth", "list"]
  serviceAccount: cgs-sa
  serviceAccountName: cgs-sa
