web-app:
  proj_identifier: platform

  namespace: samplenamespace

  google:
    domain: sampledomain.com

  api:
    label: django

  secrets:
    enabled: false

  django:
    enabled: true

  twilio:
    enabled: false

  sendgrid:
    enabled: false


