// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo_providers

import (
	"github.com/theboarderline/sample/api/src/repository"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRepository(db *gorm.DB) (*repository.Repository, error) {
	userRepository := repository.NewUserRepository(db)
	repositoryRepository := &repository.Repository{
		UserRepository: userRepository,
	}
	return repositoryRepository, nil
}
